# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('download_speed', models.CharField(max_length=10)),
                ('altitude', models.CharField(max_length=10)),
                ('pression', models.CharField(max_length=10)),
            ],
        ),
    ]
