# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(max_length=300),
        ),
    ]
